apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}
type: tls
data:
  tls.crt: {{ .Files.Get "./tls-keys/tls.crt" | b64enc | quote }}
  tls.key: {{ .Files.Get "./tls-keys/tls.key" | b64enc | quote }}
