namespace: monitoring
appname : grafana
replicaCount: 1
image:
  repository: grafana/grafana
  tag: latest
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: "0.5"
    memory: "256Mi"
  requests:
    cpu: "0.1"
    memory: "128Mi"
secretname: websitesecret
service:
  port: 3000

ingress:
  host: dlgkedemo.com
  path: /

