namespace: monitoring
appname: prometheus
replicaCount: 1

image:
  repository: prom/prometheus
  tag: latest
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: "0.5"
    memory: "256Mi"
  requests:
    cpu: "0.1"
    memory: "128Mi"

service:
  port: 9090
