name: Terraform GKE

on:
  push:
    branches:
      - main

jobs:

  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      GCP_REGION: europe-west1
      GKE_CLUSTER_NAME: gke-dlgkedmo-dev
      TKSTATE_BUCKET_NAME: dlgkedemotfstatebucket


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}' 
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        id: init
        run: |
          terraform init -backend-config="bucket=$TKSTATE_BUCKET_NAME" -backend-config="prefix=terraform/state.tfstate"

      - name: Terraform Validate
        run: terraform validate
        


      - name: Set TFVARS Path
        run: echo "TFVARS_PATH=value.tfvars" >> $GITHUB_ENV

      - name: Terraform Plan
        run: terraform plan -var-file=$TFVARS_PATH -var="gke_cluster_name=$GKE_CLUSTER_NAME"
        env:
          TFVARS_PATH: ${{ env.TFVARS_PATH }}


      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=$TFVARS_PATH -var="gke_cluster_name=$GKE_CLUSTER_NAME"
        env:
          TFVARS_PATH: ${{ env.TFVARS_PATH }}

